### ISSUE TITLE
Shared memory on Genode

### ISSUE THREAD

**Issue by senier** [Componolit/gneiss#120]
Implement using Report interface

**Comment by jklmnn** [comment]
Since the current approach doesn't seem to be possible on Genode (and also lacks some flexibility) we will split up writable and readable memory. There will be a `Rom` session that is read only and (currently) only has a client. And a `Memory` session that is always read write which will also have a server. The client is responsible to allocate the memory and pass it to the server. Both parties can write on it.

**Comment by jklmnn** [comment]
Fixed by #141.
